### ISSUE TITLE
Error make not working with node 12.06 working with 10.16 and 11.13

### ISSUE THREAD

**Issue by ManuCart** [TulipCharts/tulipnode#56]
````
pi@raspberrypi:~/btc_7b $ npm install tulind --build-from-source

> tulind@0.8.15 install /home/pi/btc_7b/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
make: Entering directory '/home/pi/btc_7b/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
In file included from ../tulind.cpp:25:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../tulind.cpp: In function ‘double* get_array(v8::Local<v8::Array>, int)’:
../tulind.cpp:38:76: error: no matching function for call to ‘v8::Value::NumberValue()’
         ret[i] = Nan::Get(input, i + offset).ToLocalChecked()->NumberValue();
                                                                            ^
In file included from /home/pi/.node-gyp/12.6.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../tulind.cpp:25:
/home/pi/.node-gyp/12.6.0/include/node/v8.h:2564:39: note: candidate: ‘v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/pi/.node-gyp/12.6.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:62:49: error: no matching function for call to ‘v8::Value::NumberValue()’
     const int index = (int)info[0]->NumberValue();
                                                 ^
In file included from /home/pi/.node-gyp/12.6.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../tulind.cpp:25:
/home/pi/.node-gyp/12.6.0/include/node/v8.h:2564:39: note: candidate: ‘v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/pi/.node-gyp/12.6.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
../tulind.cpp:72:22: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:116:49: error: no matching function for call to ‘v8::Value::NumberValue()’
     const int index = (int)info[0]->NumberValue();
                                                 ^
In file included from /home/pi/.node-gyp/12.6.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../tulind.cpp:25:
/home/pi/.node-gyp/12.6.0/include/node/v8.h:2564:39: note: candidate: ‘v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/pi/.node-gyp/12.6.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
../tulind.cpp:127:21: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
     if (ind->inputs != inputs->Length()) {
         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../tulind.cpp:134:22: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp:236:85: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated  -Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
                                                                                     ^
In file included from ../tulind.cpp:25:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../tulind.cpp:236:85: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated  -Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
                                                                                     ^
In file included from ../tulind.cpp:25:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
In file included from ../../nan/nan.h:54,
                 from ../tulind.cpp:25:
../tulind.cpp: At global scope:
/home/pi/.node-gyp/12.6.0/include/node/node.h:556:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.node-gyp/12.6.0/include/node/node.h:590:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../tulind.cpp:316:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(tulind, Init)
 ^~~~~~~~~~~
In file included from /home/pi/.node-gyp/12.6.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../tulind.cpp:25:
/home/pi/.node-gyp/12.6.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pi/.node-gyp/12.6.0/include/node/node_object_wrap.h:84:78:   required from here
/home/pi/.node-gyp/12.6.0/include/node/v8.h:9846:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.node-gyp/12.6.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.node-gyp/12.6.0/include/node/v8.h:9846:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [tulind.target.mk:109: Release/obj.target/tulind/tulind.o] Error 1
make: Leaving directory '/home/pi/btc_7b/node_modules/tulind/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.57-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/btc_7b/node_modules/tulind/lib/binding/Release/node-v72-linux-arm/tulind.node" "--module_name=tulind" "--module_path=/home/pi/btc_7b/node_modules/tulind/lib/binding/Release/node-v72-linux-arm" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/pi/btc_7b/node_modules/tulind
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/btc_7b/node_modules/tulind/lib/binding/Release/node-v72-linux-arm/tulind.node --module_name=tulind --module_path=/home/pi/btc_7b/node_modules/tulind/lib/binding/Release/node-v72-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/btc_7b/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.19.57-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/btc_7b/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/btc_7b/node_modules/tulind
node-pre-gyp ERR! node -v v12.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/btc_7b/node_modules/tulind/lib/binding/Release/node-v72-linux-arm/tulind.node --module_name=tulind --module_path=/home/pi/btc_7b/node_modules/tulind/lib/binding/Release/node-v72-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.15 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-07-22T12_15_47_597Z-debug.log
````

**Comment by codeplea** [comment]
Node 12 removed some of the V8 functions we use.

Namely, the `v8::Value::NumberValue()` function is now gone. There is a new Maybe version of it.

See the old API here: https://v8docs.nodesource.com/node-0.8/dc/d0a/classv8_1_1_value.html

And the new: https://v8docs.nodesource.com/node-10.6/dc/d0a/classv8_1_1_value.html

The problem is, if I simply shift to the new API, then it'll break building for older node versions. I'll have to mess around with it and find the best solution.

**Comment by codeplea** [comment]
I think this will be the solution: https://github.com/nodejs/nan/blob/master/doc/converters.md#api_nan_to

I'm working on a fix now.

**Comment by codeplea** [comment]
Should be fixed now. Please try again with a fresh `npm install tulind` and let me know.

**Comment by ManuCart** [comment]
Thank for this hard work.
I will check ASAP and comment

**Comment by ManuCart** [comment]
Working as expected
@codeplea your code is great and useful.
Well done thanks again for the speed patch
